server:
  port: 8080
spring:
  redis:
    database: 0
    timeout: 3000
    password: 12345678
    #sentinel:
    #  master:
    #    nodes:
    cluster:
      nodes: 192.168.0.1:6379,192.168.0.2:6379,192.168.0.3:6379
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 3000

