server:
  port: 8080
spring:
  redis:
    database: 0
    timeout: 3000
    password: 12345678
    cluster:
      nodes: 10.19.58.18:6379,10.19.58.19:6379,10.19.58.20:6379
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 3000

