server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  redis:
    database: 0
    timeout: 10000
    password: 123456789
    #sentinel:
    #  master:
    #    nodes:
    cluster:
      #nodes: 192.168.0.1:6379,192.168.0.2:6379,192.168.0.3:6379
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 5000

